interfaces:
  cli:
    name: Standard CLI Interface
    description: The standard CLI interface for the application.
    commands:
      cli.add_argument:
        arguments:
        - help: cli argument name
          name_or_flags:
          - name
          type: str
        - help: cli interface id
          name_or_flags:
          - -i
          - --interface-id
          required: true
          type: str
        - help: feature id
          name_or_flags:
          - --feature-id
          - -f
          required: true
          type: str
        - help: cli argument description
          name_or_flags:
          - -d
          - --description
          required: true
          type: str
        - choices:
          - command
          - parent_argument
          default: command
          help: cli argument type
          name_or_flags:
          - --arg-type
          type: str
        - choices:
          - str
          - int
          - float
          default: str
          help: cli argument data type
          name_or_flags:
          - --type
          type: str
        - help: optional cli argument flags
          name_or_flags:
          - --flags
          nargs: +
          type: str
        - action: store_true
          help: cli argument is required
          name_or_flags:
          - --required
          type: str
        - help: cli argument default
          name_or_flags:
          - --default
          type: str
        - action: store_true
          help: cli argument is positional
          name_or_flags:
          - --positional
          type: str
        - help: cli argument unique action
          name_or_flags:
          - --action
          type: str
        - help: cli argument value choices
          name_or_flags:
          - --choices
          nargs: +
          type: str
        - help: available number of cli argument values
          name_or_flags:
          - --nargs
          type: str
        - action: store_true
          help: convert argument value to object or object list
          name_or_flags:
          - --to-data
          type: str
        feature_id: cli.add_argument
        group_id: cli
        name: Add CLI Argument
      cli.add_command:
        arguments:
        - help: cli interface id
          name_or_flags:
          - --interface-id
          - -i
          required: true
          type: str
        - help: cli command key
          name_or_flags:
          - --command-key
          - -c
          required: true
          type: str
        - help: context group id
          name_or_flags:
          - --group-id
          - -g
          type: str
        - help: cli command name
          name_or_flags:
          - name
          type: str
        - help: cli command description
          name_or_flags:
          - --description
          - -d
          type: str
        - help: cli command feature key
          name_or_flags:
          - --feature-key
          type: str
        feature_id: cli.add_command
        group_id: cli
        name: Add CLI Command
      container.add_attribute:
        arguments:
        - help: attribute container id
          name_or_flags:
          - id
          type: str
        - help: attribute container context group id
          name_or_flags:
          - --group-id
          - -g
          required: true
          type: str
        - choices:
          - data
          - dependency
          help: attribute container type
          name_or_flags:
          - --type
          - -t
          required: true
          type: str
        - help: container attribute infrastructure flag
          name_or_flags:
          - --flag
          - -f
          required: true
          type: str
        - help: container attribute data (separated by '=')
          name_or_flags:
          - --data
          nargs: +
          required: true
          type: str
        feature_id: container.add_attribute
        group_id: container
        help: add container attribute
        name: Add Container Attribute
      error.new:
        arguments:
        - help: error name
          name_or_flags:
          - name
          type: str
        - action: append
          help: error message by lang (separated by '=')
          name_or_flags:
          - --message
          - -m
          required: true
          to_data: true
          type: str
        feature_id: error.new
        group_id: error
        help: add new error
        name: Add New Error
      feature.add_handler:
        arguments:
        - help: feature handler name
          name_or_flags:
          - name
          type: str
        - help: parent feature id
          name_or_flags:
          - --feature-id
          - -f
          required: true
          type: str
        - help: command handler attribute id
          name_or_flags:
          - --attribute-id
          - -a
          required: true
          type: str
        - help: feature handler position
          name_or_flags:
          - --position
          type: int
        - help: feature handler custom parameter
          name_or_flags:
          - --param
          nargs: +
          to_data: true
          type: str
        - help: feature handler result data key
          name_or_flags:
          - --data-key
          type: str
        - action: store_true
          help: pass on handler error
          name_or_flags:
          - --pass-on-error
          type: str
        feature_id: feature.add_handler
        group_id: feature
        help: Adds a feature handler to the feature.
        name: Add Feature Handler
      feature.new:
        arguments:
        - help: feature name
          name_or_flags:
          - name
          type: str
        - help: feature group id
          name_or_flags:
          - --group-id
          - -g
          required: true
          type: str
        - help: feature id key
          name_or_flags:
          - --feature-key
          - -f
          required: true
          type: str
        - action: append
          help: feature workflow step handler (parameters separated by '=')
          name_or_flags:
          - --handler
          to_data: true
          type: str
        - help: feature request type validator path
          name_or_flags:
          - --request-type-path
          type: str
        - help: feature description
          name_or_flags:
          - --description
          type: str
        feature_id: feature.new
        group_id: feature
        help: add new feature
        name: Add New Feature
