const:
  app_config_file: app/configs/app.yml
  error_config_file: app/configs/errors.yml
  feature_config_file: app/configs/features.yml

attrs:
  cli_interface_context:
    type: interface
    deps:
      yaml:
        class_name: CliInterfaceContext
        module_path: app.contexts.cli

  feature_context:
    type: interface
    deps:
      yaml:
        class_name: FeatureContext
        module_path: app.contexts.feature

  cli_interface_repo:
    type: data
    deps:
      yaml:
        class_name: YamlRepository
        module_path: app.repositories.cli
        params:
          app_config_file: '$c.app_config_file'

  error_repo:
    type: data
    deps:
      yaml:
        class_name: YamlRepository
        module_path: app.repositories.error
        params:
          error_config_file: '$c.error_config_file'

  feature_repo:
    type: data
    deps:
      yaml:
        class_name: YamlRepository
        module_path: app.repositories.feature
        params:
          feature_config_file: '$c.feature_config_file'

  add_cli_argument:
    type: feature
    deps:
      yaml:
        class_name: AddCliArgument
        module_path: app.commands.cli

  add_cli_command:
    type: feature
    deps:
      yaml:
        class_name: AddCliCommand
        module_path: app.commands.cli

  add_container_attribute:
    type: feature
    deps:
      yaml:
        class_name: AddContainerAttribute
        module_path: app.commands.container

  add_feature_handler:
    type: feature
    deps:
      yaml:
        class_name: AddFeatureHandler
        module_path: app.commands.feature

  add_new_error:
    type: feature
    deps:
      yaml:
        class_name: AddNewError
        module_path: app.commands.error

  add_new_feature:
    type: feature
    deps:
      yaml:
        class_name: AddNewFeature
        module_path: app.commands.feature